name: pytest

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: tests
    env:
      APP_BASE_URL: ${{ vars.APP_BASE_URL }}
      TELEGRAM_BOT_TOKEN: ${{ vars.TELEGRAM_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Show variables
        run: |
          echo "APP_BASE_URL : $APP_BASE_URL"
          echo "TELEGRAM_BOT_TOKEN : $TELEGRAM_BOT_TOKEN"
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Lint with flake8
        run: |
          python -m flake8 . --count --max-line-length=120 --statistics
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'
      - name: Test with pytest
        run: pytest --cov-config=.coveragerc --cov=app tests/ --disable-warnings -v
        env:
          DATABASE_URL_TEST: postgresql://postgres:postgres@localhost:5432/save_favourite_color_test
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
